Raise warning if shell_plus not run in debug mode
pydanny/dj-notebook pull request #100
Opened 2023-10-10 04:08 UTC by skyforest

### Summary
- This works both in a Jupyter Lab environment / notebook and at the command line.
- Covers usage of `shell_plus`
- You must have the following in installed_apps in the test project:
            "dj_notebook",
             "django_extensions",
- make sure you are using the package build on this specific branch in pip.

Examples:
![Screenshot 2023-10-09 at 11 02 02 PM](https://github.com/pydanny/dj-notebook/assets/13559970/3b522528-c269-418b-adfd-490f8487bdab)
![Screenshot 2023-10-09 at 11 03 06 PM](https://github.com/pydanny/dj-notebook/assets/13559970/2416dcf2-985c-4378-8380-b3d8082be2ca)

### For Reviewers:
1. Is this what you had in mind?
2. Should the error message text be rewritten?
3. `shell` has not been work on yet. This only works for `shell_plus` but solution should be similar.

2023-10-10 10:32 UTC, pydanny requested changes
Apologies...

I realize now that the ticket, #75 is ambiguous and you tried to get clarification. It is meant to determine if dj-notebook is run in production or not. Not to change behaviors of django-extensions (which is what this PR is about).

This pull request could readily be adapted as a change to django-extensions itself. And arguably belongs there and not in dj-notebook. I'm happy to help you make that contribution to that library.

For dj-notebook, I was thinking of something like this within the `activate` function:

```python
def activate():
   # snip
   if plus.settings.DEBUG == False:
       # log warning message to stdout
```

2023-10-10 10:32 UTC, pydanny commented on src/dj_notebook/__init__.py
> +def is_notebook():
I did not expect this to ever be called outside of a Jupyter notebook. Is that a thing for your team?

2023-10-10 10:32 UTC, pydanny commented on src/dj_notebook/management/commands/shell_plus.py
> +from django_extensions.management.commands import shell_plus
I think I did not define the scope of this correctly. It is not meant to warn off on django-extension's `shell_plus`, rather to detect if dj-notebook is being run in production.

2023-10-11 03:26 UTC, skyforest commented
@pydanny, you know, that does seem much more reasonable of an ask for this :) Well, it was interesting to implement this but I think it is better off being a learning experience than a potential feature request over at django-extensions. I'm going to close this PR and get a fresh branch for what is actually needed. Thanks!

2023-10-11 03:26 UTC, closed without merging